feat : NG_BACK_END-126
nrhirano/school012 pull request #1
Opened 2021-12-22 05:34 UTC by nrhirano

#### 関連タスク
- [NG_BACK_END-126 【第12回スクール宿題】 (平野様)](https://nishio-pj.backlog.com/view/NG_BACK_END-126)

#### PR 概要
- 第12回スクールの宿題です。

#### 相談したい項目・保留した項目
- なし

#### 参考資料
- なし

2021-12-22 08:39 UTC, GenkiHirano commented on homework012/sort_user.go
> +	user := []User{}
![badge](https://img.shields.io/badge/review-imo-orange.svg)
userは複数入ることが想定されるので、usersの方が適切だと思います。
ascUsersも同様です。

2021-12-23 01:21 UTC, GenkiHirano approved these changes
LGTM 🎁

2021-12-23 09:37 UTC, GenkiHirano commented on homework012/sort_user.go
> +	for _, user := range users {
こちらの問題、仕様を満たしているので正解です⭕️
補足ですが下記の様に`insertUsers関数`内で、配列で定義することもできます。

```
users := []User{
		{
			ID:    1,
			Name:  "田中太郎",
			Class: 1,
			Age:   20,
		}, {
			ID:    2,
			Name:  "鈴木晴香",
			Class: 1,
			Age:   25,
		}, {
			ID:    3,
			Name:  "大森拓也",
			Class: 1,
			Age:   30,
		},
	}
```

2021-12-27 03:59 UTC, EikoNakashima requested changes
コメントしました。
ご確認お願い致します。

2021-12-27 03:59 UTC, EikoNakashima commented on homework012/sort_user.go
> +		_, err := engine.Table("user").Insert(user)
```suggestion
		_, err := engine.Table("user").Insert(users)
```
このように配列をそのままInsertする事も出来ます。

2021-12-27 03:59 UTC, EikoNakashima commented on homework012/sort_user.go
> +	err := session.OrderBy("id DESC").Find(&users)
```suggestion
	err := session.Asc("id").Find(&users)
```

ASCとDESCが逆になっていると思います。
また、上記のようにも書けます。

2021-12-27 03:59 UTC, EikoNakashima commented on homework012/sort_user.go
> +	err := session.OrderBy("id Asc").Find(&users)
```suggestion
	err := session.Desc("id").Find(&users)
```

ASCとDESCが逆になっていると思います。
また、上記のようにも書けます。

2021-12-27 07:15 UTC, EikoNakashima approved these changes
LGTM❄️

2021-12-27 07:18 UTC, merged